### ISSUE TITLE
Geisterupload: Zuerst nur Hash hochladen?

### ISSUE THREAD

**Issue by killerbees19** [froonix/happytec-ghosttool#99]
Sobald serverseitig die vierte Version des Geistparsers (und damit das Ghost-DB-Format 2) eingesetzt wird, würde es reichen den Hash hochzuladen, um zu sehen, ob es den Geist schon gibt bzw. welche ID dieser hat. Statt 10-20 Kilobyte müssten somit nur noch 136 Byte (Hex) hochgeladen und verglichen werden.

Der neue einheitliche Hash wird folgendes Format haben: `<LENGTH><SHA512>`

Entweder binär (68 Byte) oder als Hexcode (136 Byte; vorzugsweise Kleinbuchstaben). Die ersten 32 Bit (der Binärdaten!) enthalten die Länge der Geistdaten. Der Rest ist die SHA512-Summe der Geistdaten. Als Geistdaten zählen ausschließlich die Binärdaten des `Data`-Attributs – **nicht** der ganze XML-Tag und auch **nicht** der Base64-String!

Aktuell (Geistparser v3; [Legacy] Ghost-DB-Format 1) wird ein spezieller MD5-Hash verwendet, der sich außerdem zwischen v1 und v2 nochmals unterscheidet. Dieser kann clientseitig nicht berechnet werden!

**Comment by killerbees19** [comment]
Die neue API-Methode `ghost.id` (_derzeit nur auf DEV im ghosts-v2 Branch_) unterstützt die Parameter `byHash` und `byHashes`. Wenn kein einziger Geist gefunden wird, wird ein 404er mit dem Fehler `GHOST_UNKNOWN` zurückgegeben. Das Ausgabeformat ist wie bei `ghost.put`:

```xml
<?xml version="1.0" encoding="utf-8"?>
<GhostList>
	 <Ghost ID="224">
		<GhostHash>000015193785f76d2057d918f099035516e88e88596d28df34409ff8a24804de529173d026504de2ff1fabcefaa63a75d98ab99cd06c3bc5db226e126f12067b00ee2d2d</GhostHash>
	</Ghost>
	<Ghost ID="98">
		<GhostHash>00001bce176b0710254f8a1dafe5db39231cbe01fe4ebe062a23ecbc92d81b3cc70101f84d74d37142c56f86a67207de913a8c1a3cbd1a3d635d744974a4c679fd65ca43</GhostHash>
	</Ghost>
</GhostList>
```

Empfehlungen für HTGT:

* API-Client für `ghost.id` erweitern.
* Neue "Hash" Klasse, die Hash/ID Zuordnungen mindestens im Arbeitsspeicher hält.
* Die Zuordnungen **müssen** auch bei `ghost.put` und `ghost.get` aktualisiert werden!
* Vor dem Upload von Geistern prüfen, ob die ID anhand des Hashes (lokal) bereits bekannt ist.
* Vor dem Upload von Geistern zuerst (gesammelt) die existierenden IDs anhand des Hashes abrufen.
* Erst danach einen Upload ausführen, außer der Upload wurde erzwungen. (sehr sinnvoll für FFM!)

Eventuell wäre es sinnvoll, Hash/ID Zuordnungen in einem permanenten Cache abzulegen?

Zusätzlich sollte man sich überlegen, wie man #92 sinnvoll implementiert.

**Comment by IceflowRE** [comment]
`Wenn kein einziger Geist gefunden wird, wird ein 404er mit dem Fehler GHOST_UNKNOWN zurückgegeben.`
Der 404 Error ist in diesem Fall der falsche Code, besser wäre ein 204er. (https://www.restapitutorial.com/httpstatuscodes.html)

**Comment by killerbees19** [comment]
> Der 404 Error ist in diesem Fall der falsche Code, besser wäre ein 204er.

So sehr ich Deine Argumente unterstütze, leider ist es bei der eSports-API derzeit keine Option. Würde die API einen Statuscode 204 zurückgeben, kann der Body nicht mehr ausgewertet werden, da er laut Statuscode ja leer ist. Im Body ist derzeit aber (neben dem Header `X-API-Error`) der Fehlercode enthalten, der zur Generierung einer hilfreichen Fehlermeldung notwendig ist. Darauf verlässt sich nicht nur die HTGT.app sondern z.B. auch das Spiel selbst beim x-Tries-Cup.

Ich habe das gerade extra nochmals ausgetestet und bin damit mächtig auf die Nase gefallen… 😀
